version: 2.1
##
# The config will be executed on each pull_request update due to the GitHub Workflow.
# Each push will also trigger the config, due to default CircleCI's behavior.
##

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - run: npm install
      - run: npm test

workflows:
  test:
    # This workflow is set to be conditionally triggered, only when
    # the GitHub Action is triggered.
    # With no other workflows, normal push events will be ignored currently.
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - test
