name: Staging-App
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: read

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: xt0rted/pull-request-comment-branch@v1
        if: steps.check.outputs.triggered == 'true'
        id: comment-branch
      - name: parse comment body    
        if: steps.check.outputs.triggered == 'true'
        run: echo "STAGING_ENV=$(echo ${{ steps.check.outputs.comment_body }} | sed 's/@deploy//' | xargs)"  >> $GITHUB_ENV
      - uses: ./
        if: steps.check.outputs.triggered == 'true'
        with:
          PR_Headref: ${{ steps.get-branch.outputs.branch }}
          GHA_Meta: ${{ env.STAGING_ENV }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
